"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Eye, MapPin, Package, Printer, RefreshCw, Search, X } from "lucide-react";
import { supabase } from "../../../lib/supabase";

type Order={id:string;customer_name:string;customer_phone:string;customer_address:string;notes:string;payment_method:string;status:string;subtotal:number;delivery_fee:number;total:number;created_at:string;delivery_method:string;delivery_distance_km:number|null};
type Item={id:string;order_id:string;product_id:string|null;product_name:string;price:number;quantity:number;notes:string|null};
const ADMIN_EMAIL="maspri2904@gmail.com";
const money=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
const shortId=(id:string)=>id.slice(0,8).toUpperCase();
const statusLabel:Record<string,string>={pending:"Pesanan masuk",processing:"Diproses",delivering:"Diantar",completed:"Selesai",cancelled:"Dibatalkan"};
const paymentLabel:Record<string,string>={cod:"Tunai",qris:"QRIS",transfer:"Transfer"};

export default function AdminOrders(){
 const[orders,setOrders]=useState<Order[]>([]),[filter,setFilter]=useState("active"),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[selected,setSelected]=useState<Order|null>(null),[items,setItems]=useState<Item[]>([]),[busy,setBusy]=useState("");
 const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);const{data:u}=await supabase.auth.getUser();if(!u.user||u.user.email?.toLowerCase()!==ADMIN_EMAIL){location.href="/admin/login";return}const{data,error:e}=await supabase.from("orders").select("id,customer_name,customer_phone,customer_address,notes,payment_method,status,subtotal,delivery_fee,total,created_at,delivery_method,delivery_distance_km").order("created_at",{ascending:false}).limit(100);if(e)setError(e.message);else setOrders((data||[]) as Order[]);if(!silent)setLoading(false)},[]);
 useEffect(()=>{void load();const t=setInterval(()=>void load(true),7000);return()=>clearInterval(t)},[load]);
 const visible=useMemo(()=>orders.filter(o=>{const mf=filter==="active"?["pending","processing","delivering"].includes(o.status):filter==="history"?["completed","cancelled"].includes(o.status):o.status===filter;const q=query.trim().toLowerCase();return mf&&(!q||o.customer_name.toLowerCase().includes(q)||o.id.toLowerCase().includes(q)||o.customer_phone.includes(q))}),[orders,filter,query]);
 const open=async(o:Order)=>{setSelected(o);setItems([]);const{data,error:e}=await supabase.from("order_items").select("id,order_id,product_id,product_name,price,quantity,notes").eq("order_id",o.id).order("created_at");if(e)setError(e.message);else setItems((data||[]) as Item[])};
 const updateStatus=async(o:Order,next:string)=>{setBusy(o.id);setError("");const{error:e}=await supabase.from("orders").update({status:next,updated_at:new Date().toISOString()}).eq("id",o.id);if(e)setError(e.message);else{setOrders(xs=>xs.map(x=>x.id===o.id?{...x,status:next}:x));setSelected(x=>x&&x.id===o.id?{...x,status:next}:x)}setBusy("")};
 const logout=async()=>{await supabase.auth.signOut();location.href="/admin/login"};
 if(loading)return <main className="min-h-screen grid place-items-center bg-[#07090d] text-white"><div className="text-center"><div className="mx-auto mb-3 h-9 w-9 animate-spin rounded-full border-2 border-white/10 border-t-emerald-400"/><p className="text-sm text-zinc-500">Memuat pesanan...</p></div></main>;
 return <main className="min-h-screen bg-[#07090d] text-zinc-100 pb-24"><header className="sticky top-0 z-40 border-b border-white/[.07] bg-[#080b10]/95 px-4 py-3 backdrop-blur-xl"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-3"><div className="flex items-center gap-3"><button onClick={()=>location.href="/admin/pos"} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 text-zinc-400"><ArrowLeft size={18}/></button><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-emerald-300">Operasional</p><h1 className="text-lg font-black">Pesanan Online</h1></div></div><div className="flex items-center gap-2"><button onClick={()=>void load()} className="rounded-xl border border-white/10 p-2 text-zinc-400" title="Refresh"><RefreshCw size={17}/></button><button onClick={()=>void logout()} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-bold text-zinc-400">Keluar</button></div></div></header>
 <div className="mx-auto max-w-[1500px] p-4 md:p-6"><div className="mb-5 grid grid-cols-2 gap-2 sm:grid-cols-4"><Stat label="Masuk" value={orders.filter(o=>o.status==="pending").length}/><Stat label="Diproses" value={orders.filter(o=>o.status==="processing").length}/><Stat label="Diantar" value={orders.filter(o=>o.status==="delivering").length}/><Stat label="Selesai" value={orders.filter(o=>o.status==="completed").length}/></div>
  <div className="mb-4 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-2 overflow-x-auto">{[["active","Aktif"],["pending","Masuk"],["processing","Diproses"],["delivering","Diantar"],["history","Riwayat"]].map(([v,l])=><button key={v} onClick={()=>setFilter(v)} className={`shrink-0 rounded-full px-4 py-2.5 text-xs font-black ${filter===v?"bg-emerald-400 text-[#06110c]":"border border-white/10 bg-white/[.03] text-zinc-500"}`}>{l}</button>)}</div><div className="relative w-full lg:max-w-xs"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-600"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari nama / ID / HP" className="h-11 w-full rounded-xl border border-white/10 bg-black/20 pl-9 pr-3 text-sm outline-none"/></div></div>
  {error&&<div className="mb-4 rounded-2xl border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-300">⚠️ {error}</div>}
  <div className="space-y-3">{visible.map(o=><OrderCard key={o.id} order={o} busy={busy===o.id} onOpen={()=>void open(o)} onStatus={next=>void updateStatus(o,next)}/>)}</div>{visible.length===0&&<div className="rounded-3xl border border-dashed border-white/10 p-14 text-center text-zinc-600"><Package className="mx-auto mb-3"/><p className="font-bold">Belum ada pesanan di sini.</p></div>}
 </div>
 {selected&&<OrderModal order={selected} items={items} onClose={()=>setSelected(null)} onStatus={next=>void updateStatus(selected,next)}/>}<style>{`@media print{body *{visibility:hidden!important}.admin-receipt,.admin-receipt *{visibility:visible!important}.admin-receipt{position:absolute!important;left:0!important;top:0!important;width:80mm!important;padding:4mm!important;background:#fff!important;color:#000!important;font-family:monospace!important}.admin-receipt *{color:#000!important}@page{size:80mm auto;margin:0}}`}</style>
 </main>;
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/[.07] bg-[#101419] p-4"><p className="text-[10px] font-black uppercase tracking-[.18em] text-zinc-600">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>}
function OrderCard({order,busy,onOpen,onStatus}:{order:Order;busy:boolean;onOpen:()=>void;onStatus:(s:string)=>void}){const pickup=order.delivery_method==="pickup";return <article className="rounded-[24px] border border-white/[.07] bg-[#101419] p-4"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${order.status==="pending"?"bg-amber-400/10 text-amber-300":order.status==="completed"?"bg-emerald-400/10 text-emerald-300":order.status==="cancelled"?"bg-red-400/10 text-red-300":"bg-sky-400/10 text-sky-300"}`}>{statusLabel[order.status]||order.status}</span><span className="rounded-full bg-white/[.05] px-2.5 py-1 text-[10px] font-bold text-zinc-500">{pickup?"Pickup":"Delivery"}</span><span className="text-[10px] text-zinc-600">#{shortId(order.id)}</span></div><h2 className="mt-2 truncate text-base font-black">{order.customer_name}</h2><p className="mt-1 text-xs text-zinc-500">{new Date(order.created_at).toLocaleString("id-ID")} · {paymentLabel[order.payment_method]||order.payment_method}</p>{!pickup&&<p className="mt-1 flex items-center gap-1 truncate text-xs text-zinc-600"><MapPin size={13}/> {order.customer_address||"Alamat tidak ada"}</p>}</div><div className="flex items-center justify-between gap-3 sm:justify-end"><div className="text-right"><p className="text-xs text-zinc-600">Total</p><p className="text-lg font-black text-emerald-300">{money(order.total)}</p></div><button onClick={onOpen} className="grid h-11 w-11 place-items-center rounded-xl border border-white/10 text-zinc-400" title="Detail"><Eye size={17}/></button>{order.status==="pending"&&<button disabled={busy} onClick={()=>onStatus("processing")} className="rounded-xl bg-emerald-400 px-3 py-3 text-xs font-black text-[#06110c]">Terima</button>}{order.status==="processing"&&<button disabled={busy} onClick={()=>onStatus(pickup?"completed":"delivering")} className="rounded-xl bg-emerald-400 px-3 py-3 text-xs font-black text-[#06110c]">{pickup?"Selesaikan":"Siap Diantar"}</button>}{order.status==="delivering"&&!pickup&&<span className="rounded-xl border border-amber-400/20 bg-amber-400/10 px-3 py-3 text-center text-[11px] font-black text-amber-300">Menunggu konfirmasi pelanggan</span>}</div></div></article>}
function OrderModal({order,items,onClose,onStatus}:{order:Order;items:Item[];onClose:()=>void;onStatus:(s:string)=>void}){const[picking,setPicking]=useState(false);const pickup=order.delivery_method==="pickup";return <div className="fixed inset-0 z-[110] overflow-y-auto bg-black/75 p-3 backdrop-blur-sm"><div className="mx-auto my-4 max-w-2xl rounded-[28px] border border-white/10 bg-[#101419] p-4 shadow-2xl sm:p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-emerald-300">Detail transaksi</p><h2 className="mt-1 text-xl font-black">#{shortId(order.id)}</h2><p className="mt-1 text-xs text-zinc-500">{new Date(order.created_at).toLocaleString("id-ID")}</p></div><button onClick={onClose} className="rounded-xl border border-white/10 p-2"><X size={17}/></button></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><Info label="Pelanggan" value={order.customer_name}/><Info label="No. HP" value={order.customer_phone||"-"}/><Info label="Pembayaran" value={paymentLabel[order.payment_method]||order.payment_method}/><Info label="Jenis" value={pickup?"Ambil sendiri":"Delivery"}/></div>{!pickup&&<div className="mt-3 rounded-2xl bg-black/20 p-3 text-sm"><p className="text-[10px] font-black uppercase tracking-widest text-zinc-600">Alamat</p><p className="mt-1">{order.customer_address||"-"}</p>{order.delivery_distance_km!=null&&<p className="mt-1 text-xs text-zinc-600">Jarak ± {Number(order.delivery_distance_km).toFixed(2)} km · Ongkir {money(order.delivery_fee)}</p>}</div>}
 <div className="mt-4 space-y-2">{items.map(i=><div key={i.id} className="flex items-center justify-between rounded-2xl bg-black/20 p-3"><div><p className="text-sm font-bold">{i.product_name}</p><p className="text-xs text-zinc-600">{i.quantity} × {money(i.price)}</p></div><b>{money(i.price*i.quantity)}</b></div>)}</div><div className="mt-4 border-t border-white/10 pt-4"><div className="flex justify-between text-sm text-zinc-500"><span>Subtotal</span><span>{money(order.subtotal)}</span></div><div className="mt-1 flex justify-between text-sm text-zinc-500"><span>Ongkir</span><span>{money(order.delivery_fee)}</span></div><div className="mt-2 flex justify-between text-lg font-black"><span>Total</span><span className="text-emerald-300">{money(order.total)}</span></div></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>{setPicking(true);setTimeout(()=>window.print(),80)}} className="rounded-xl border border-white/10 px-4 py-3 text-xs font-black"><Printer size={15} className="mr-2 inline"/>Cetak Struk</button>{order.status==="pending"&&<button onClick={()=>onStatus("processing")} className="rounded-xl bg-emerald-400 px-4 py-3 text-xs font-black text-[#06110c]">Terima Pesanan</button>}{order.status==="processing"&&<button onClick={()=>onStatus(pickup?"completed":"delivering")} className="rounded-xl bg-emerald-400 px-4 py-3 text-xs font-black text-[#06110c]">{pickup?"Selesaikan":"Siap Diantar"}</button>}{order.status==="delivering"&&!pickup&&<span className="rounded-xl border border-amber-400/20 bg-amber-400/10 px-4 py-3 text-xs font-black text-amber-300">Menunggu konfirmasi pelanggan</span>}</div><div className="admin-receipt fixed -left-[9999px] top-0">{picking&&<><div style={{textAlign:"center"}}><b style={{fontSize:18}}>RUMAH MAKAN</b><div>Struk Pembayaran</div></div><div>--------------------------------</div><div>No: #{shortId(order.id)}</div><div>{new Date(order.created_at).toLocaleString("id-ID")}</div><div>Pelanggan: {order.customer_name}</div><div>--------------------------------</div>{items.map(i=><div key={i.id} style={{marginBottom:4}}>{i.product_name}<br/>{i.quantity} x {money(i.price)} = {money(i.price*i.quantity)}</div>)}<div>--------------------------------</div><div>Subtotal {money(order.subtotal)}</div><div>Ongkir   {money(order.delivery_fee)}</div><b>TOTAL    {money(order.total)}</b><div>Bayar: {paymentLabel[order.payment_method]||order.payment_method}</div><div style={{textAlign:"center",marginTop:12}}>Terima kasih 🙏</div></>}</div></div></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-black/20 p-3"><p className="text-[10px] font-black uppercase tracking-widest text-zinc-600">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div>}
