"use client";

import { useCallback, useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";

type Order = { id:string; customer_name:string; customer_phone:string; customer_address:string; payment_method:string; status:string; subtotal:number; delivery_fee:number; total:number; created_at:string };
type Product = { id:string; name:string; category:string; price:number; stock:number; is_available:boolean };
type OrderItem = { id:string; product_name:string; price:number; quantity:number; notes:string|null };
const money=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
const statuses=["pending","processing","completed","cancelled"];
const label=(s:string)=>({pending:"Menunggu",processing:"Diproses",completed:"Selesai",cancelled:"Dibatalkan"}[s]||s);
const ADMIN_EMAIL="maspri2904@gmail.com";

export default function AdminPage(){
 const [orders,setOrders]=useState<Order[]>([]); const [products,setProducts]=useState<Product[]>([]); const [email,setEmail]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const [selected,setSelected]=useState<Order|null>(null); const [items,setItems]=useState<OrderItem[]>([]); const [detailLoading,setDetailLoading]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError(""); const {data:userData}=await supabase.auth.getUser(); if(!userData.user||userData.user.email?.toLowerCase()!==ADMIN_EMAIL){location.href="/admin/login";return;} setEmail(userData.user.email||""); const [o,p]=await Promise.all([supabase.from("orders").select("id,customer_name,customer_phone,customer_address,payment_method,status,subtotal,delivery_fee,total,created_at").order("created_at",{ascending:false}).limit(50),supabase.from("products").select("id,name,category,price,stock,is_available").order("created_at")]); if(o.error||p.error)setError(o.error?.message||p.error?.message||"Gagal memuat data"); setOrders((o.data||[]) as Order[]); setProducts((p.data||[]) as Product[]);setLoading(false);},[]);
 useEffect(()=>{load(); const ch=supabase.channel("admin-orders").on("postgres_changes",{event:"*",schema:"public",table:"orders"},()=>load()).subscribe(); return()=>{supabase.removeChannel(ch);};},[load]);
 async function updateStatus(id:string,status:string){const {error}=await supabase.from("orders").update({status}).eq("id",id);if(error)setError(error.message);else load();}
 async function openDetail(order:Order){setSelected(order);setItems([]);setDetailLoading(true);const {data,error}=await supabase.from("order_items").select("id,product_name,price,quantity,notes").eq("order_id",order.id).order("created_at");if(error)setError(error.message);else setItems((data||[]) as OrderItem[]);setDetailLoading(false);}
 async function logout(){await supabase.auth.signOut();location.href="/admin/login";}
 const revenue=orders.filter(o=>o.status!=="cancelled").reduce((s,o)=>s+o.total,0), pending=orders.filter(o=>o.status==="pending").length, active=products.filter(p=>p.is_available).length;
 if(loading)return <main className="min-h-screen bg-zinc-950 p-8 text-white"><p className="text-zinc-500">Memuat dashboard...</p></main>;
 return <main className="min-h-screen bg-zinc-950 text-white"><div className="mx-auto max-w-7xl p-5 md:p-8"><header className="mb-8 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-zinc-500">Admin · {email}</p><h1 className="mt-1 text-2xl font-bold">Dashboard Penjualan</h1></div><div className="flex flex-wrap gap-2"><button onClick={load} className="rounded-xl border border-zinc-800 px-4 py-2 text-sm">Refresh</button><button onClick={()=>location.href="/admin/products"} className="rounded-xl bg-emerald-500 px-4 py-2 text-sm font-semibold text-zinc-950">Produk</button><button onClick={()=>location.href="/admin/delivery"} className="rounded-xl border border-zinc-800 px-4 py-2 text-sm">🚚 Ongkir</button><button onClick={logout} className="rounded-xl bg-zinc-800 px-4 py-2 text-sm">Keluar</button></div></header>{error&&<p className="mb-5 rounded-xl border border-red-900 bg-red-950/40 p-3 text-sm text-red-400">{error}</p>}
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Penjualan","money",money(revenue)],["Pesanan", "",orders.length],["Menunggu","",pending],["Produk Aktif","",active]].map(([a,,b])=><div key={a} className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><p className="text-sm text-zinc-500">{a}</p><p className="mt-2 text-2xl font-bold">{b}</p></div>)}</div>
 <section className="mt-6 rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold">Pesanan Terbaru</h2><p className="text-xs text-zinc-500">Klik pesanan untuk melihat rincian.</p></div><span className="text-xs text-zinc-500">{orders.length} terbaru</span></div>{orders.length===0?<p className="py-10 text-center text-zinc-500">Belum ada pesanan.</p>:<div className="space-y-3">{orders.map(o=><article key={o.id} onClick={()=>openDetail(o)} className="cursor-pointer rounded-xl border border-zinc-800 p-4 transition hover:border-zinc-700"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="font-semibold">{o.customer_name} <span className="text-xs font-normal text-zinc-600">#{o.id.slice(0,8)}</span></p><p className="mt-1 text-sm text-zinc-500">{o.customer_phone} · {o.payment_method.toUpperCase()}</p><p className="mt-1 text-xs text-zinc-600">{o.customer_address}</p></div><div className="flex items-center gap-3"><strong>{money(o.total)}</strong><select value={o.status} onClick={e=>e.stopPropagation()} onChange={e=>updateStatus(o.id,e.target.value)} className="rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm">{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></div></div></article>)}</div>}</section>
 <section className="mt-6 rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><h2 className="font-semibold">Produk</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{products.map(p=><div key={p.id} className="rounded-xl border border-zinc-800 p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{p.name}</p><p className="text-xs text-zinc-500">{p.category} · {money(p.price)}</p></div><span className={`text-xs ${p.stock<10?"text-red-400":"text-emerald-400"}`}>Stok {p.stock}</span></div></div>)}</div></section>
 </div>
 {selected&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/80 p-4" onClick={()=>setSelected(null)}><div className="mx-auto mt-6 max-w-lg rounded-3xl border border-zinc-800 bg-zinc-900 p-5" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-emerald-400">Detail Pesanan</p><h2 className="mt-1 text-xl font-bold">#{selected.id.slice(0,8)}</h2></div><button onClick={()=>setSelected(null)} className="rounded-lg bg-zinc-800 px-3 py-2">✕</button></div><div className="mt-5 space-y-2 rounded-2xl bg-zinc-950 p-4 text-sm"><p><span className="text-zinc-500">Pelanggan:</span> {selected.customer_name}</p><p><span className="text-zinc-500">WhatsApp:</span> {selected.customer_phone}</p><p><span className="text-zinc-500">Alamat:</span> {selected.customer_address}</p><p><span className="text-zinc-500">Pembayaran:</span> {selected.payment_method.toUpperCase()}</p><p><span className="text-zinc-500">Status:</span> {label(selected.status)}</p></div><h3 className="mt-5 font-semibold">Item Pesanan</h3>{detailLoading?<p className="py-5 text-center text-zinc-500">Memuat item...</p>:items.length===0?<p className="py-5 text-center text-zinc-500">Tidak ada item.</p>:<div className="mt-3 space-y-2">{items.map(item=><div key={item.id} className="rounded-xl border border-zinc-800 p-3"><div className="flex justify-between gap-3"><div><p className="font-medium">{item.product_name}</p><p className="text-xs text-zinc-500">{item.quantity} × {money(item.price)}</p>{item.notes&&<p className="mt-1 text-xs text-amber-400">Catatan: {item.notes}</p>}</div><strong>{money(item.price*item.quantity)}</strong></div></div>)}</div>}<div className="mt-5 space-y-2 border-t border-zinc-800 pt-4 text-sm"><div className="flex justify-between"><span className="text-zinc-500">Subtotal</span><span>{money(selected.subtotal)}</span></div><div className="flex justify-between"><span className="text-zinc-500">Ongkir</span><span>{money(selected.delivery_fee)}</span></div><div className="flex justify-between text-lg font-bold"><span>Total</span><span>{money(selected.total)}</span></div></div></div></div>}
 </main>;
}
