"use client";
import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../../../lib/supabase";

type Courier={id:string;name:string;phone:string|null;is_active:boolean;created_at:string};
const empty={name:"",phone:"",email:"",password:""};
export default function CouriersPage(){
 const[couriers,setCouriers]=useState<Courier[]>([]),[form,setForm]=useState(empty),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[msg,setMsg]=useState("");
 async function request(method="GET",body?:unknown){const{data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token){location.href="/admin/login";throw new Error("Sesi admin berakhir.")}const r=await fetch("/api/admin/couriers",{method,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Permintaan gagal");return j}
 async function load(){setLoading(true);setError("");try{const j=await request();setCouriers(j.couriers||[])}catch(e){setError(e instanceof Error?e.message:"Gagal memuat kurir.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function create(e:FormEvent){e.preventDefault();setSaving(true);setError("");setMsg("");try{await request("POST",form);setForm(empty);setMsg("Akun kurir berhasil dibuat.");await load()}catch(e){setError(e instanceof Error?e.message:"Gagal membuat akun.")}finally{setSaving(false)}}
 async function toggle(c:Courier){try{await request("PATCH",{id:c.id,is_active:!c.is_active});await load()}catch(e){setError(e instanceof Error?e.message:"Gagal mengubah status.")}}
 async function remove(c:Courier){if(!window.confirm(`Hapus akun kurir ${c.name}?`))return;try{await request("DELETE",{id:c.id});setMsg("Akun kurir dihapus.");await load()}catch(e){setError(e instanceof Error?e.message:"Gagal menghapus akun.")}}
 return <main className="min-h-screen bg-zinc-950 p-4 text-white md:p-8"><div className="mx-auto max-w-5xl"><button onClick={()=>location.href="/admin"} className="mb-5 text-sm text-zinc-500 hover:text-zinc-300">← Dashboard</button><div className="mb-6"><p className="text-sm font-bold text-emerald-400">MANAJEMEN AKSES</p><h1 className="mt-1 text-3xl font-black">Akun Kurir</h1><p className="mt-1 text-sm text-zinc-500">Hanya admin yang dapat membuat dan mengelola akun kurir.</p></div>{error&&<p className="mb-4 rounded-2xl border border-red-900 bg-red-950/40 p-4 text-sm text-red-300">⚠️ {error}</p>}{msg&&<p className="mb-4 rounded-2xl border border-emerald-900 bg-emerald-950/30 p-4 text-sm text-emerald-300">✓ {msg}</p>}
 <div className="grid gap-5 lg:grid-cols-[380px_1fr]"><form onSubmit={create} className="rounded-3xl border border-zinc-800 bg-zinc-900 p-5 shadow-xl"><h2 className="text-lg font-black">Buat akun baru</h2><p className="mt-1 text-xs text-zinc-500">Akun langsung aktif dan bisa login.</p><div className="mt-5 space-y-3">{[["Nama","name","text","Nama kurir"],["No. HP","phone","tel","08xxxxxxxxxx"],["Email","email","email","kurir@email.com"],["Password","password","password","Minimal 8 karakter"]].map(([label,key,type,placeholder])=><label key={key} className="block text-sm">{label}<input required={key!=="phone"} type={type} value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-950 p-3 outline-none focus:border-emerald-500" /></label>)}</div><button disabled={saving} className="mt-5 w-full rounded-xl bg-emerald-500 py-3 font-bold text-zinc-950 disabled:opacity-50">{saving?"Membuat akun...":"+ Buat Akun Kurir"}</button></form>
 <section className="rounded-3xl border border-zinc-800 bg-zinc-900 p-5 shadow-xl"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Daftar Kurir</h2><p className="text-xs text-zinc-500">{couriers.length} akun terdaftar</p></div><button onClick={()=>void load()} className="rounded-xl border border-zinc-700 px-3 py-2 text-xs">↻ Refresh</button></div>{loading?<div className="mt-5 space-y-3">{[1,2,3].map(i=><div key={i} className="h-20 animate-pulse rounded-2xl bg-zinc-800/60"/>)}</div>:couriers.length===0?<div className="py-14 text-center text-zinc-500">🛵<p className="mt-2 font-semibold">Belum ada akun kurir</p></div>:<div className="mt-5 space-y-3">{couriers.map(c=><article key={c.id} className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h3 className="font-bold">{c.name}</h3><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${c.is_active?"bg-emerald-950 text-emerald-300":"bg-zinc-800 text-zinc-500"}`}>{c.is_active?"AKTIF":"NONAKTIF"}</span></div><p className="mt-1 text-xs text-zinc-500">{c.phone||"No. HP belum diisi"}</p></div><div className="flex gap-2"><button onClick={()=>void toggle(c)} className="rounded-xl border border-zinc-700 px-3 py-2 text-xs font-semibold">{c.is_active?"Nonaktifkan":"Aktifkan"}</button><button onClick={()=>void remove(c)} className="rounded-xl bg-red-950 px-3 py-2 text-xs font-semibold text-red-300">Hapus</button></div></div></article>)}</div>}</section></div></div></main>;
}
