"use client";

import { useEffect, useState } from "react";
import { supabase } from "../../../lib/supabase";

const ADMIN_EMAIL = "maspri2904@gmail.com";
const money = (n:number) => new Intl.NumberFormat("id-ID", {style:"currency", currency:"IDR", maximumFractionDigits:0}).format(n);

type Settings = { restaurant_lat:number|null; restaurant_lng:number|null; base_fee:number; per_km_fee:number; free_shipping_minimum:number };

export default function DeliveryPage(){
 const [s,setS]=useState<Settings>({restaurant_lat:null,restaurant_lng:null,base_fee:5000,per_km_fee:2000,free_shipping_minimum:50000});
 const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [msg,setMsg]=useState(""); const [error,setError]=useState("");
 useEffect(()=>{(async()=>{const {data:u}=await supabase.auth.getUser();if(u.user?.email?.toLowerCase()!==ADMIN_EMAIL){location.href="/admin/login";return;}const {data,error}=await supabase.from("delivery_settings").select("restaurant_lat,restaurant_lng,base_fee,per_km_fee,free_shipping_minimum").eq("id",1).single();if(error)setError(error.message);else if(data)setS(data);setLoading(false);})();},[]);
 function setNum(k:keyof Settings,v:string){setS(x=>({...x,[k]:v===""?null:Number(v)}));}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setMsg("");setError("");const {error}=await supabase.from("delivery_settings").update(s).eq("id",1);if(error)setError(error.message);else setMsg("Pengaturan ongkir berhasil disimpan.");setSaving(false);}
 if(loading)return <main className="min-h-screen bg-zinc-950 p-6 text-white">Memuat pengaturan...</main>;
 return <main className="min-h-screen bg-zinc-950 p-5 text-white"><div className="mx-auto max-w-lg"><button onClick={()=>location.href="/admin"} className="mb-6 text-sm text-zinc-500">← Dashboard</button><h1 className="text-2xl font-bold">Pengaturan Ongkir</h1><p className="mt-1 text-sm text-zinc-500">Atur lokasi rumah makan dan tarif pengantaran.</p><form onSubmit={save} className="mt-7 space-y-4 rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><div><h2 className="font-semibold">Lokasi Rumah Makan</h2><p className="mt-1 text-xs text-zinc-500">Ambil koordinat dari Google Maps atau GPS.</p></div><label className="block text-sm">Latitude<input type="number" step="any" value={s.restaurant_lat ?? ""} onChange={e=>setNum("restaurant_lat",e.target.value)} className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-950 p-3 outline-none focus:border-emerald-500" placeholder="-6.200000" /></label><label className="block text-sm">Longitude<input type="number" step="any" value={s.restaurant_lng ?? ""} onChange={e=>setNum("restaurant_lng",e.target.value)} className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-950 p-3 outline-none focus:border-emerald-500" placeholder="106.816666" /></label><div className="border-t border-zinc-800 pt-4"><h2 className="font-semibold">Tarif</h2></div><label className="block text-sm">Ongkir dasar (Rp)<input type="number" min="0" value={s.base_fee} onChange={e=>setS(x=>({...x,base_fee:Number(e.target.value)}))} className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-950 p-3" /></label><label className="block text-sm">Tambahan per km (Rp)<input type="number" min="0" value={s.per_km_fee} onChange={e=>setS(x=>({...x,per_km_fee:Number(e.target.value)}))} className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-950 p-3" /></label><label className="block text-sm">Gratis ongkir minimal belanja (Rp)<input type="number" min="0" value={s.free_shipping_minimum} onChange={e=>setS(x=>({...x,free_shipping_minimum:Number(e.target.value)}))} className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-950 p-3" /></label>{s.restaurant_lat!=null&&s.restaurant_lng!=null&&<p className="rounded-xl bg-zinc-950 p-3 text-xs text-zinc-400">Contoh: belanja di bawah {money(s.free_shipping_minimum)} akan dikenakan ongkir dasar {money(s.base_fee)} + {money(s.per_km_fee)}/km.</p>}{error&&<p className="rounded-xl border border-red-900 bg-red-950/40 p-3 text-sm text-red-400">{error}</p>}{msg&&<p className="rounded-xl border border-emerald-900 bg-emerald-950/40 p-3 text-sm text-emerald-400">{msg}</p>}<button disabled={saving} className="w-full rounded-xl bg-emerald-500 py-3 font-semibold text-zinc-950 disabled:opacity-50">{saving?"Menyimpan...":"Simpan Pengaturan"}</button></form></div></main>;
}
