"use client";
import { useCallback, useEffect, useState } from "react";
import { Bell, Check, ChevronRight, Clock3, MapPin, X } from "lucide-react";
import { supabase } from "../lib/supabase";

type Order={id:string;created_at:string;customer_name:string;customer_phone:string;customer_address:string;notes:string;payment_method:string;payment_note:string|null;status:string;subtotal:number;delivery_fee:number;total:number;delivery_method:string};
const money=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
const shortId=(id:string)=>id.slice(0,8).toUpperCase();
const payment=(v:string)=>v==="qris"?"QRIS":v==="transfer"?"Transfer":"Tunai";

export default function AdminIncomingOrders(){
 const[orders,setOrders]=useState<Order[]>([]),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[selected,setSelected]=useState<Order|null>(null),[updating,setUpdating]=useState(false),[known,setKnown]=useState<string[]>([]);
 const load=useCallback(async()=>{const{data}=await supabase.from("orders").select("id,created_at,customer_name,customer_phone,customer_address,notes,payment_method,payment_note,status,subtotal,delivery_fee,total,delivery_method").in("status",["pending","processing"]).not("payment_note","like","%· POS").order("created_at",{ascending:false}).limit(30);setOrders((data||[]) as Order[])},[]);
 useEffect(()=>{let mounted=true;(async()=>{await load();if(!mounted)return;})();const id=setInterval(load,5000);return()=>{mounted=false;clearInterval(id)}},[load]);
 const pending=orders.filter(o=>o.status==="pending");
 useEffect(()=>{if(!pending.length)return;const fresh=pending.filter(o=>!known.includes(o.id));if(fresh.length){setOpen(true);setKnown(p=>[...p,...fresh.map(o=>o.id)].slice(-100));try{navigator.vibrate?.([100,60,100])}catch{}}},[pending,known]);
 async function setStatus(status:"processing"|"cancelled"){if(!selected)return;setUpdating(true);const{error}=await supabase.from("orders").update({status}).eq("id",selected.id);if(!error){setSelected(null);await load()}setUpdating(false)}
 return <>{pending.length>0&&<button onClick={()=>setOpen(true)} className="admin-incoming-trigger fixed right-4 top-4 z-[95] flex items-center gap-2 rounded-2xl border border-amber-300/20 bg-[#17130b]/95 px-3 py-2.5 text-xs font-black text-amber-200 shadow-2xl shadow-black/30 backdrop-blur-xl"><span className="relative grid h-7 w-7 place-items-center rounded-xl bg-amber-400 text-black"><Bell size={15}/><span className="absolute -right-1 -top-1 grid h-4 min-w-4 place-items-center rounded-full bg-red-500 px-1 text-[9px] text-white">{pending.length>9?"9+":pending.length}</span></span>Pesanan masuk</button>}
 {open&&<div className="fixed inset-0 z-[110] bg-black/70 p-3 backdrop-blur-sm"><div className="absolute right-3 top-3 flex h-[calc(100vh-24px)] w-[min(460px,calc(100vw-24px))] flex-col overflow-hidden rounded-[30px] border border-white/10 bg-[#0d1117] shadow-2xl"><header className="flex items-center justify-between border-b border-white/10 p-4"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-amber-300">Kasir</p><h2 className="text-xl font-black">Pesanan Online</h2><p className="mt-1 text-xs text-zinc-500">{pending.length} pesanan menunggu</p></div><button onClick={()=>setOpen(false)} className="rounded-xl border border-white/10 p-2"><X size={17}/></button></header><div className="flex-1 overflow-y-auto p-3">{orders.length===0?<div className="grid h-full place-items-center text-center text-zinc-600"><div><Check className="mx-auto mb-2"/><p className="font-bold">Tidak ada pesanan aktif</p></div></div>:<div className="space-y-2">{orders.map(o=><button key={o.id} onClick={()=>setSelected(o)} className="w-full rounded-2xl border border-white/[.07] bg-white/[.03] p-3 text-left hover:border-emerald-400/30"><div className="flex items-start justify-between gap-3"><div><b className="text-sm">#{shortId(o.id)}</b><p className="mt-1 text-xs font-bold">{o.customer_name}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-black ${o.status==="pending"?"bg-amber-400/10 text-amber-300":"bg-blue-400/10 text-blue-300"}`}>{o.status==="pending"?"BARU":"DIPROSES"}</span></div><div className="mt-3 flex items-center justify-between text-xs text-zinc-500"><span><Clock3 size={13} className="mr-1 inline"/>{new Date(o.created_at).toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"})}</span><b className="text-emerald-300">{money(o.total)}</b></div></button>)}</div>}</div></div></div>}
 {selected&&<div className="fixed inset-0 z-[120] grid place-items-center bg-black/75 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-[28px] border border-white/10 bg-[#11161c] p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-emerald-300">Detail pesanan</p><h3 className="mt-1 text-xl font-black">#{shortId(selected.id)}</h3></div><button onClick={()=>setSelected(null)} className="rounded-xl border border-white/10 p-2"><X size={16}/></button></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-white/[.04] p-3"><span className="text-zinc-600">Pelanggan</span><b className="mt-1 block">{selected.customer_name}</b></div><div className="rounded-xl bg-white/[.04] p-3"><span className="text-zinc-600">Pembayaran</span><b className="mt-1 block">{payment(selected.payment_method)}</b></div></div><div className="mt-2 rounded-xl bg-white/[.04] p-3 text-xs"><span className="text-zinc-600">Alamat</span><p className="mt-1 leading-5"><MapPin size={13} className="mr-1 inline text-emerald-300"/>{selected.customer_address||"-"}</p></div><div className="mt-2 flex items-center justify-between rounded-xl bg-emerald-400/10 p-3"><span className="text-xs text-zinc-500">Total</span><b className="text-lg text-emerald-300">{money(selected.total)}</b></div><div className="mt-4 flex gap-2">{selected.status==="pending"&&<button disabled={updating} onClick={()=>void setStatus("processing")} className="flex-1 rounded-2xl bg-emerald-400 px-4 py-3 text-xs font-black text-[#06110c]">{updating?"Memproses...":"✓ Terima & Proses"}</button>}<button disabled={updating} onClick={()=>void setStatus("cancelled")} className="rounded-2xl border border-red-400/20 px-4 py-3 text-xs font-black text-red-300">Batalkan</button><button onClick={()=>setSelected(null)} className="rounded-2xl border border-white/10 px-4 py-3 text-xs font-black">Tutup</button></div><button onClick={()=>{setSelected(null);setOpen(false);location.href="/admin/orders"}} className="mt-2 flex w-full items-center justify-center gap-1 py-2 text-xs font-bold text-zinc-500">Buka pengelolaan pesanan <ChevronRight size={14}/></button></div></div>}
 </>;
}
