"use client";

import { useState } from "react";

export default function CheckoutPage() {
  const [sent, setSent] = useState(false);
  if (sent) return <main className="flex min-h-screen items-center justify-center bg-zinc-950 p-5"><div className="w-full max-w-md rounded-3xl border border-zinc-800 bg-zinc-900 p-8 text-center"><div className="text-5xl">✅</div><h1 className="mt-5 text-2xl font-bold">Pesanan berhasil!</h1><p className="mt-2 text-zinc-500">Pesananmu sudah diterima. Tunggu konfirmasi dari rumah makan.</p><button onClick={() => location.href = "/menu"} className="mt-6 w-full rounded-xl bg-emerald-500 py-3 font-semibold text-zinc-950">Kembali ke Menu</button></div></main>;
  return <main className="min-h-screen bg-zinc-950 p-5"><div className="mx-auto max-w-lg"><button onClick={() => history.back()} className="mb-6 text-sm text-zinc-500">← Kembali</button><h1 className="text-2xl font-bold">Checkout</h1><p className="mt-1 text-sm text-zinc-500">Lengkapi data untuk mengirim pesanan.</p><form onSubmit={e => { e.preventDefault(); setSent(true); }} className="mt-7 space-y-4"><label className="block text-sm">Nama<input required className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-900 p-3 outline-none focus:border-emerald-500" placeholder="Nama lengkap" /></label><label className="block text-sm">No. WhatsApp<input required type="tel" className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-900 p-3 outline-none focus:border-emerald-500" placeholder="08xxxxxxxxxx" /></label><label className="block text-sm">Alamat<textarea required rows={3} className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-900 p-3 outline-none focus:border-emerald-500" placeholder="Alamat pengantaran" /></label><label className="block text-sm">Catatan pesanan<textarea rows={2} className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-900 p-3 outline-none focus:border-emerald-500" placeholder="Contoh: sambalnya dipisah" /></label><label className="block text-sm">Metode pembayaran<select className="mt-2 w-full rounded-xl border border-zinc-800 bg-zinc-900 p-3 outline-none"><option>COD</option><option>Transfer Bank</option><option>QRIS</option></select></label><button className="w-full rounded-xl bg-emerald-500 py-3.5 font-semibold text-zinc-950">Kirim Pesanan</button></form></div></main>;
}
