"use client";

import { useEffect, useRef, useState } from "react";
import LiveMap from "../../components/LiveMap";
import { supabase } from "../../lib/supabase";

const REST_LAT=-7.396963,REST_LNG=109.199585;
const maps=(lat:number,lng:number,originLat?:number|null,originLng?:number|null)=>{
 const origin=originLat!=null&&originLng!=null?`${originLat},${originLng}`:`${REST_LAT},${REST_LNG}`;
 return `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${lat},${lng}&travelmode=driving`;
};

type Order={id:string;customer_name:string;customer_address:string;status:string;delivery_method:string;customer_lat:number|null;customer_lng:number|null;courier_lat:number|null;courier_lng:number|null;courier_updated_at:string|null;courier_tracking:boolean};

export default function CourierPage(){
 const[id,setId]=useState("");const[order,setOrder]=useState<Order|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(false);const[tracking,setTracking]=useState(false);const watch=useRef<number|null>(null);
 async function load(oid:string){const{data,error:e}=await supabase.rpc("get_order_status",{p_order_id:oid});if(e){setError(e.message);return null}const o=data as Order;setOrder(o);setTracking(Boolean(o?.courier_tracking));return o;}
 async function open(e:React.FormEvent){e.preventDefault();const v=id.trim();if(!v)return;setLoading(true);setError("");const o=await load(v);setLoading(false);if(o&&!o.id)setError("Pesanan tidak ditemukan.");}
 async function send(lat:number,lng:number){if(!id)return;const{error:e}=await supabase.rpc("update_courier_location",{p_order_id:id,p_lat:lat,p_lng:lng});if(e)setError(e.message);else setOrder(o=>o?{...o,courier_lat:lat,courier_lng:lng,courier_updated_at:new Date().toISOString(),courier_tracking:true}:o);}
 async function start(){if(!navigator.geolocation){setError("Browser ini tidak mendukung GPS.");return}setError("");const{error:e}=await supabase.rpc("set_courier_tracking",{p_order_id:id,p_enabled:true});if(e){setError(e.message);return}setTracking(true);watch.current=navigator.geolocation.watchPosition(p=>send(p.coords.latitude,p.coords.longitude),e=>setError(`GPS: ${e.message}`),{enableHighAccuracy:true,maximumAge:3000,timeout:10000});}
 async function stop(){if(watch.current!=null)navigator.geolocation.clearWatch(watch.current);watch.current=null;await supabase.rpc("set_courier_tracking",{p_order_id:id,p_enabled:false});setTracking(false);await load(id);}
 useEffect(()=>()=>{if(watch.current!=null)navigator.geolocation.clearWatch(watch.current)},[]);
 const points=order?[{lat:REST_LAT,lng:REST_LNG,label:"Rumah makan",emoji:"🏠",className:"bg-emerald-500"},...(order.customer_lat!=null&&order.customer_lng!=null?[{lat:order.customer_lat,lng:order.customer_lng,label:"Pelanggan",emoji:"📍",className:"bg-blue-500"}]:[]),...(order.courier_lat!=null&&order.courier_lng!=null?[{lat:order.courier_lat,lng:order.courier_lng,label:tracking?"Kurir · LIVE":"Kurir",emoji:"🛵",className:"bg-orange-500"}]:[])]:[];
 const hasCustomer=order?.customer_lat!=null&&order?.customer_lng!=null;
 const navigationUrl=hasCustomer?maps(order!.customer_lat!,order!.customer_lng!,order!.courier_lat,order!.courier_lng):"";
 return <main className="min-h-screen bg-zinc-950 p-5 text-white"><div className="mx-auto max-w-lg"><button onClick={()=>location.href="/admin"} className="mb-6 text-sm text-zinc-500">← Dashboard</button><div className="text-center"><div className="text-5xl">🛵</div><h1 className="mt-3 text-2xl font-bold">Live Tracking Kurir</h1><p className="mt-1 text-sm text-zinc-500">GPS HP kurir akan tampil di peta pelanggan.</p></div><form onSubmit={open} className="mt-7 flex gap-2"><input value={id} onChange={e=>setId(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-zinc-800 bg-zinc-900 p-3 text-sm outline-none focus:border-emerald-500" placeholder="Nomor pesanan"/><button disabled={loading} className="rounded-xl bg-emerald-500 px-4 py-3 text-sm font-semibold text-zinc-950">{loading?"Cek...":"Buka"}</button></form>{error&&<p className="mt-4 rounded-xl border border-red-900 bg-red-950/40 p-3 text-sm text-red-400">{error}</p>}{order&&<section className="mt-5 overflow-hidden rounded-3xl border border-zinc-800 bg-zinc-900"><div className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-zinc-500">Pesanan #{order.id.slice(0,8)}</p><h2 className="mt-1 font-bold">{order.customer_name}</h2><p className="mt-1 text-xs text-zinc-500">{order.customer_address}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${tracking?"bg-emerald-500 text-zinc-950":"bg-zinc-800 text-zinc-400"}`}>{tracking?"● LIVE":"OFF"}</span></div></div><LiveMap points={points}/><div className="p-5"><div className="grid grid-cols-2 gap-2"><button onClick={tracking?stop:start} className={`rounded-xl py-3 text-sm font-bold ${tracking?"bg-red-500 text-white":"bg-emerald-500 text-zinc-950"}`}>{tracking?"⏹ Hentikan OTW":"▶️ Mulai OTW"}</button>{hasCustomer&&<a href={navigationUrl} target="_blank" rel="noreferrer" className="rounded-xl border border-zinc-700 py-3 text-center text-sm font-semibold">🧭 Rute ke Pelanggan</a>}</div><div className="mt-3 rounded-xl border border-zinc-800 bg-zinc-950 p-3 text-xs text-zinc-400">📍 {order.courier_lat!=null?"Rute dimulai dari posisi GPS kurir saat ini.":"Mulai OTW untuk mendapatkan posisi GPS kurir."}</div><div className="mt-3 rounded-xl bg-zinc-950 p-3 text-xs text-zinc-500">{order.courier_updated_at?`GPS terakhir: ${new Date(order.courier_updated_at).toLocaleTimeString("id-ID")}`:"GPS kurir belum tersedia."} · Update otomatis tiap beberapa detik.</div></div></section>}</div></main>;
}
