"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "../../../lib/supabase";
type OrderStatus={id:string;status:string;delivery_method:"delivery"|"pickup";customer_lat:number|null;customer_lng:number|null;delivery_distance_km:number|null;delivery_fee:number;total:number;created_at:string};
const RESTAURANT_LAT=-7.396963,RESTAURANT_LNG=109.199585;
const steps=["pending","processing","completed"];const labels:Record<string,string>={pending:"Pesanan diterima",processing:"Sedang diproses",completed:"Pesanan selesai",cancelled:"Pesanan dibatalkan"};const rupiah=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
export default function StatusPage(){const[id,setId]=useState("");const[order,setOrder]=useState<OrderStatus|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const check=useCallback(async(orderId:string)=>{if(!orderId)return;const{data,error:e}=await supabase.rpc("get_order_status",{p_order_id:orderId});if(e){setError(e.message);return}if(!data){setError("Pesanan tidak ditemukan. Periksa nomor pesanan.");return}setError("");setOrder(data as OrderStatus)},[]);
useEffect(()=>{const saved=sessionStorage.getItem("dasboard_order_id")||"";if(saved){setId(saved);check(saved)}},[check]);useEffect(()=>{if(!order?.id||order.status==="completed"||order.status==="cancelled")return;const t=window.setInterval(()=>check(order.id),5000);return()=>window.clearInterval(t)},[order?.id,order?.status,check]);async function submit(e:React.FormEvent){e.preventDefault();const v=id.trim();if(!v)return;setLoading(true);setError("");sessionStorage.setItem("dasboard_order_id",v);await check(v);setLoading(false)}
const cancelled=order?.status==="cancelled",current=order?steps.indexOf(order.status):-1;const mapUrl=useMemo(()=>order?.customer_lat!=null&&order?.customer_lng!=null?`https://www.google.com/maps/dir/?api=1&origin=${RESTAURANT_LAT},${RESTAURANT_LNG}&destination=${order.customer_lat},${order.customer_lng}&travelmode=driving`:"",[order]);
return <main className="min-h-screen bg-zinc-950 p-5 text-white"><div className="mx-auto max-w-md"><button onClick={()=>location.href="/menu"} className="mb-6 text-sm text-zinc-500">← Kembali ke Menu</button><div className="text-center"><div className="text-5xl">📦</div><h1 className="mt-3 text-2xl font-bold">Status Pesanan</h1><p className="mt-1 text-sm text-zinc-500">Perubahan status diperbarui otomatis.</p></div><form onSubmit={submit} className="mt-7 flex gap-2"><input value={id} onChange={e=>setId(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-zinc-800 bg-zinc-900 p-3 text-sm outline-none focus:border-emerald-500" placeholder="Masukkan nomor pesanan"/><button disabled={loading} className="rounded-xl bg-emerald-500 px-4 py-3 text-sm font-semibold text-zinc-950">{loading?"Cek...":"Cek"}</button></form>{error&&<p className="mt-4 rounded-xl border border-red-900 bg-red-950/40 p-3 text-sm text-red-400">{error}</p>}
{order&&<section className="mt-5 rounded-3xl border border-zinc-800 bg-zinc-900 p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs text-zinc-500">Nomor Pesanan</p><p className="mt-1 break-all font-mono text-sm">{order.id}</p></div><span className="rounded-full bg-zinc-800 px-3 py-1 text-xs">{order.delivery_method==="delivery"?"🚚 Diantar":"🏠 Ambil sendiri"}</span></div><div className="mt-7 text-center"><div className="text-4xl">{cancelled?"❌":order.status==="completed"?"✅":order.status==="processing"?"👨‍🍳":"🕐"}</div><h2 className="mt-2 text-xl font-bold">{labels[order.status]||order.status}</h2></div>{!cancelled&&<div className="mt-7 space-y-4">{steps.map((step,i)=><div key={step} className="flex items-center gap-3"><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-sm font-bold ${i<=current?"bg-emerald-500 text-zinc-950":"bg-zinc-800 text-zinc-500"}`}>{i<=current?"✓":i+1}</div><p className={`font-medium ${i<=current?"text-white":"text-zinc-500"}`}>{labels[step]}</p></div>)}</div>}
{order.delivery_method==="delivery"&&!cancelled&&order.customer_lat!=null&&order.customer_lng!=null&&<div className="mt-6 overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-950"><div className="p-4"><p className="font-semibold">🗺️ Rute Pengantaran</p><p className="mt-1 text-xs text-zinc-500">Rumah makan → Lokasi pelanggan</p></div><div className="relative h-44 overflow-hidden border-y border-zinc-800 bg-[radial-gradient(circle_at_20%_35%,rgba(16,185,129,.12),transparent_28%),radial-gradient(circle_at_78%_65%,rgba(59,130,246,.12),transparent_28%),linear-gradient(135deg,transparent_49%,rgba(255,255,255,.06)_50%,transparent_51%)]"><div className="absolute left-[17%] top-[31%] text-center"><div className="mx-auto flex h-10 w-10 items-center justify-center rounded-full bg-emerald-500 text-lg shadow-lg">🏠</div><p className="mt-1 rounded-md bg-zinc-900/90 px-2 py-1 text-[10px]">Rumah makan</p></div><svg className="absolute inset-0 h-full w-full" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="M22 35 C 35 18, 42 78, 57 53 S 70 57, 80 65" fill="none" stroke="currentColor" strokeWidth="1.2" strokeDasharray="3 2" className="text-emerald-400"/></svg><div className="absolute right-[14%] top-[55%] text-center"><div className="mx-auto flex h-10 w-10 items-center justify-center rounded-full bg-blue-500 text-lg shadow-lg">📍</div><p className="mt-1 rounded-md bg-zinc-900/90 px-2 py-1 text-[10px]">Pelanggan</p></div></div><div className="grid grid-cols-2 gap-2 p-4 text-xs"><div className="rounded-xl bg-zinc-900 p-3"><p className="text-zinc-500">Jarak</p><p className="mt-1 font-semibold">{order.delivery_distance_km!=null?`${Number(order.delivery_distance_km).toFixed(1)} km`:"-"}</p></div><div className="rounded-xl bg-zinc-900 p-3"><p className="text-zinc-500">Ongkir</p><p className="mt-1 font-semibold">{rupiah(order.delivery_fee||0)}</p></div></div><a href={mapUrl} target="_blank" rel="noreferrer" className="mx-4 mb-4 block rounded-xl bg-emerald-500 py-3 text-center text-sm font-bold text-zinc-950">📍 Buka Google Maps & Rute</a></div>}
{order.delivery_method==="pickup"&&!cancelled&&<div className="mt-6 rounded-2xl border border-zinc-800 bg-zinc-950 p-4 text-center text-sm text-zinc-400">🏠 Pesanan diambil sendiri. Tidak ada ongkir dan GPS.</div>}{cancelled&&<div className="mt-6 rounded-xl bg-red-950/40 p-3 text-center text-sm text-red-400">Pesanan ini dibatalkan oleh admin.</div>}<div className="mt-6 border-t border-zinc-800 pt-4 flex justify-between text-sm"><span className="text-zinc-500">Total</span><span className="font-bold">{rupiah(order.total||0)}</span></div></section>}<div className="mt-5 text-center"><button onClick={()=>location.href="/menu"} className="text-sm text-emerald-400">Pesan lagi</button></div></div></main>}
