"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import LiveMap from "../../../components/LiveMap";
import { supabase } from "../../../lib/supabase";
type OrderStatus={id:string;status:string;delivery_method:"delivery"|"pickup";customer_lat:number|null;customer_lng:number|null;delivery_distance_km:number|null;delivery_fee:number;total:number;created_at:string;courier_lat:number|null;courier_lng:number|null;courier_updated_at:string|null;courier_tracking:boolean;delivery_arrival_requested_at:string|null;delivery_confirmed_at:string|null};
type History={id:string;name:string;phone:string;total:number;deliveryMethod:string;createdAt:string};
const HISTORY_KEY="dasboard_order_history",RESTAURANT_LAT=-7.396963,RESTAURANT_LNG=109.199585,steps=["pending","processing","delivering","completed"];
const labels:Record<string,string>={pending:"Pesanan diterima",processing:"Sedang diproses",delivering:"Sedang diantar",completed:"Pesanan selesai",cancelled:"Pesanan dibatalkan"};
const rupiah=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
export default function StatusPage(){
 const[id,setId]=useState(""),[order,setOrder]=useState<OrderStatus|null>(null),[history,setHistory]=useState<History[]>([]),[loading,setLoading]=useState(false),[confirming,setConfirming]=useState(false),[error,setError]=useState("");
 const loadHistory=useCallback(()=>{try{const data=JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]");setHistory(Array.isArray(data)?data:[])}catch{setHistory([])}},[]);
 const check=useCallback(async(orderId:string)=>{if(!orderId)return;const{data,error:e}=await supabase.rpc("get_order_status",{p_order_id:orderId});if(e){setError(e.message);return}if(!data){setError("Pesanan tidak ditemukan. Periksa nomor pesanan.");return}setError("");setOrder(data as OrderStatus)},[]);
 useEffect(()=>{loadHistory();const saved=sessionStorage.getItem("dasboard_order_id")||"";if(saved){setId(saved);check(saved)}},[check,loadHistory]);
 useEffect(()=>{if(!order?.id||order.status==="completed"||order.status==="cancelled")return;const t=window.setInterval(()=>check(order.id),3000);return()=>window.clearInterval(t)},[order?.id,order?.status,check]);
 async function submit(e:React.FormEvent){e.preventDefault();const v=id.trim();if(!v)return;setLoading(true);setError("");sessionStorage.setItem("dasboard_order_id",v);await check(v);setLoading(false)}
 async function confirmReceived(){if(!order||confirming||order.delivery_method!=="delivery"||!order.delivery_arrival_requested_at||order.status!=="delivering")return;const ok=window.confirm("Konfirmasi bahwa pesanan sudah benar-benar kamu terima?\n\nSetelah disetujui, status pesanan menjadi Selesai.");if(!ok)return;setConfirming(true);setError("");const{data,error:e}=await supabase.rpc("confirm_delivery_received",{p_order_id:order.id});if(e)setError(`Gagal mengonfirmasi penerimaan: ${e.message}`);else if(!data)setError("Pesanan belum siap dikonfirmasi atau sudah berubah.");else await check(order.id);setConfirming(false)}
 function openHistory(h:History){setId(h.id);sessionStorage.setItem("dasboard_order_id",h.id);void check(h.id)}
 function deleteHistory(orderId:string){const next=history.filter(h=>h.id!==orderId);setHistory(next);localStorage.setItem(HISTORY_KEY,JSON.stringify(next));if(id===orderId){setId("");setOrder(null);sessionStorage.removeItem("dasboard_order_id")}}
 function clearHistory(){if(!window.confirm("Hapus semua riwayat pesanan di perangkat ini?"))return;localStorage.removeItem(HISTORY_KEY);setHistory([])}
 const cancelled=order?.status==="cancelled",current=order?steps.indexOf(order.status):-1,isPickup=order?.delivery_method==="pickup";const mapUrl=useMemo(()=>!isPickup&&order?.customer_lat!=null&&order?.customer_lng!=null?`https://www.google.com/maps/dir/?api=1&origin=${RESTAURANT_LAT},${RESTAURANT_LNG}&destination=${order.customer_lat},${order.customer_lng}&travelmode=driving`:"",[order,isPickup]);
 const points=!isPickup&&order?[{lat:RESTAURANT_LAT,lng:RESTAURANT_LNG,label:"Rumah makan",emoji:"🏠",className:"bg-emerald-500"},...(order.customer_lat!=null&&order.customer_lng!=null?[{lat:order.customer_lat,lng:order.customer_lng,label:"Pelanggan",emoji:"📍",className:"bg-blue-500"}]:[]),...(order.courier_lat!=null&&order.courier_lng!=null?[{lat:order.courier_lat,lng:order.courier_lng,label:order.courier_tracking?"Kurir · LIVE":"Kurir",emoji:"🛵",className:"bg-orange-500"}]:[])]:[];
 const statusTitle=isPickup?(order?.status==="processing"?"Pesanan siap diambil di rumah makan":order?.status==="pending"?"Pesanan diterima":order?.status==="completed"?"Pesanan sudah diambil":"Pesanan sedang disiapkan"):order?.courier_tracking?"Kurir sedang OTW":labels[order?.status||""]||order?.status;
 return <main className="min-h-screen bg-zinc-950 p-5 text-white"><div className="mx-auto max-w-md"><button onClick={()=>location.href="/menu"} className="mb-6 text-sm text-zinc-500">← Kembali ke Menu</button><div className="text-center"><div className="text-5xl">📦</div><h1 className="mt-3 text-2xl font-bold">Status Pesanan</h1><p className="mt-1 text-sm text-zinc-500">Status dan posisi kurir diperbarui otomatis.</p></div>
 {history.length>0&&<section className="mt-6 rounded-3xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex items-center justify-between gap-3"><div><h2 className="font-bold">🕘 Riwayat Pesanan</h2><p className="mt-1 text-xs text-zinc-500">Tersimpan lokal di perangkat ini.</p></div><button onClick={clearHistory} className="text-xs text-red-400">Hapus semua</button></div><div className="mt-3 space-y-2">{history.map(h=><div key={h.id} className="flex items-center gap-2 rounded-2xl border border-zinc-800 bg-zinc-950 p-3"><button onClick={()=>openHistory(h)} className="min-w-0 flex-1 text-left"><p className="font-semibold">{h.name} · {rupiah(h.total)}</p><p className="mt-1 truncate text-xs text-zinc-500">#{h.id.slice(0,8)} · {h.deliveryMethod==="delivery"?"Diantar":"Ambil sendiri"} · {new Date(h.createdAt).toLocaleString("id-ID")}</p></button><button onClick={()=>deleteHistory(h.id)} className="rounded-lg px-2 py-2 text-zinc-500">✕</button></div>)}</div></section>}
 <form onSubmit={submit} className="mt-6 flex gap-2"><input value={id} onChange={e=>setId(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-zinc-800 bg-zinc-900 p-3 text-sm outline-none focus:border-emerald-500" placeholder="Masukkan nomor pesanan"/><button disabled={loading} className="rounded-xl bg-emerald-500 px-4 py-3 text-sm font-semibold text-zinc-950">{loading?"Cek...":"Cek"}</button></form>{error&&<p className="mt-4 rounded-xl border border-red-900 bg-red-950/40 p-3 text-sm text-red-400">{error}</p>}
 {order&&<section className="mt-5 rounded-3xl border border-zinc-800 bg-zinc-900 p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs text-zinc-500">Nomor Pesanan</p><p className="mt-1 break-all font-mono text-sm">{order.id}</p></div><span className="rounded-full bg-zinc-800 px-3 py-1 text-xs">{isPickup?"🏠 Ambil sendiri":"🚚 Diantar"}</span></div><div className="mt-7 text-center"><div className="text-4xl">{cancelled?"❌":order.status==="completed"?"✅":order.courier_tracking?"🛵":isPickup?"🏠":"👨‍🍳"}</div><h2 className="mt-2 text-xl font-bold">{statusTitle}</h2>{isPickup&&order.status==="processing"&&<div className="mt-4 rounded-2xl border border-emerald-800 bg-emerald-950/30 p-4 text-sm text-emerald-200">🏠 Pesanan sudah diproses. Silakan ambil di rumah makan. Tidak perlu GPS dan tidak ada ongkir.</div>}{order.status==="delivering"&&order.delivery_arrival_requested_at&&<div className="mt-4 rounded-2xl border border-blue-800 bg-blue-950/30 p-4"><p className="font-semibold text-blue-200">🤝 Kurir menyatakan pesanan sudah sampai</p><p className="mt-1 text-xs text-zinc-400">Pesanan belum selesai sampai kamu menyetujui bahwa barang sudah diterima.</p><button onClick={confirmReceived} disabled={confirming} className="mt-3 w-full rounded-xl bg-emerald-500 py-3 text-sm font-bold text-zinc-950 disabled:opacity-50">{confirming?"⏳ Mengonfirmasi...":"✅ Saya Sudah Menerima Pesanan"}</button></div>}</div>
 {!cancelled&&<div className="mt-7 space-y-4">{steps.filter(s=>!isPickup||s!=="delivering").map((step,i)=>{const pickupSteps=steps.filter(s=>s!=="delivering");const idx=pickupSteps.indexOf(order.status),si=pickupSteps.indexOf(step);return <div key={step} className="flex items-center gap-3"><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-sm font-bold ${si<=idx?"bg-emerald-500 text-zinc-950":"bg-zinc-800 text-zinc-500"}`}>{si<=idx?"✓":si+1}</div><p className={`font-medium ${si<=idx?"text-white":"text-zinc-500"}`}>{isPickup&&step==="processing"?"Siap diambil":labels[step]}</p></div>})}</div>}
 {!isPickup&&order.delivery_method==="delivery"&&!cancelled&&order.customer_lat!=null&&order.customer_lng!=null&&<div className="mt-6 overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-950"><div className="p-4"><div className="flex items-center justify-between"><div><p className="font-semibold">🗺️ Live Tracking</p><p className="mt-1 text-xs text-zinc-500">Rute mengikuti jalan asli · posisi kurir real-time</p></div>{order.courier_tracking&&<span className="rounded-full bg-red-500 px-2 py-1 text-[10px] font-bold text-white">● LIVE</span>}</div></div><LiveMap points={points}/>{order.courier_tracking&&<div className="border-t border-zinc-800 bg-emerald-950/20 p-3 text-center text-xs text-emerald-300">🛵 Kurir sedang menuju lokasi kamu</div>}<div className="grid grid-cols-2 gap-2 p-4 text-xs"><div className="rounded-xl bg-zinc-900 p-3"><p className="text-zinc-500">Jarak pengantaran</p><p className="mt-1 font-semibold">{order.delivery_distance_km!=null?`${Number(order.delivery_distance_km).toFixed(1)} km`:"-"}</p></div><div className="rounded-xl bg-zinc-900 p-3"><p className="text-zinc-500">Ongkir</p><p className="mt-1 font-semibold">{rupiah(order.delivery_fee||0)}</p></div></div><a href={mapUrl} target="_blank" rel="noreferrer" className="mx-4 mb-4 block rounded-xl bg-emerald-500 py-3 text-center text-sm font-bold text-zinc-950">📍 Buka Google Maps & Rute</a></div>}
 {isPickup&&!cancelled&&<div className="mt-6 rounded-2xl border border-zinc-800 bg-zinc-950 p-4 text-center text-sm text-zinc-400">🏠 Ambil sendiri di rumah makan · Ongkir Rp0 · GPS tidak diperlukan.</div>}{cancelled&&<div className="mt-6 rounded-xl bg-red-950/40 p-3 text-center text-sm text-red-400">Pesanan ini dibatalkan oleh admin.</div>}<div className="mt-6 border-t border-zinc-800 pt-4 flex justify-between text-sm"><span className="text-zinc-500">Total</span><span className="font-bold">{rupiah(order.total||0)}</span></div></section>}<div className="mt-5 text-center"><button onClick={()=>location.href="/menu"} className="text-sm text-emerald-400">Pesan lagi</button></div></div></main>;
}
